import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-gray-800 w-full h-screen flex justify-center items-center'>
        <h1 className='text-white text-6xl uppercase'>Ici miel ici</h1>
      </div>

    </div>
  )
}

export default Home
